const Nogizaka46Members = [
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/e/e8/NishinoKaerimichi.jpg',
    gen: '1st',
    romaji: 'Nishino Nanase',
    kanji: '西野七瀬',
    nickname: 'Naachan (なーちゃん)',
    birthday: '1994/05/25',
    birthPlace: 'Osaka, Japan',
    bloodType: 'O',
    age: '25 Years Old',
    height: '159cm',
    imgUrl: '/nogizaka46/members/1st-Nishino Nanase-Osaka Japan.jpg',
    birthdayStr: '1994-05-25'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/a/a4/HoshinoKaerimichi.jpg',
    gen: '1st',
    romaji: 'Hoshino Minami',
    kanji: '星野みなみ',
    nickname: 'Minami (みなみ)  Hoshimina (ほしみな)',
    birthday: '1998/02/06',
    birthPlace: 'Chiba, Japan',
    bloodType: 'B',
    age: '22 Years Old',
    height: '155cm',
    imgUrl: '/nogizaka46/members/1st-Hoshino Minami-Chiba Japan.jpg',
    birthdayStr: '1998-02-06'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/a/a5/ShiraishiKaerimichi.jpg',
    gen: '1st',
    romaji: 'Shiraishi Mai',
    kanji: '白石麻衣',
    nickname: 'Maiyan (まいやん)',
    birthday: '1992/08/20',
    birthPlace: 'Gunma, Japan',
    bloodType: 'A',
    age: '27 Years Old',
    height: '162cm',
    imgUrl: '/nogizaka46/members/1st-Shiraishi Mai-Gunma Japan.jpg',
    birthdayStr: '1992-08-20'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/3/3a/SaitoYuriKaerimichi.jpg',
    gen: '1st',
    romaji: 'Saito Yuri',
    kanji: '斉藤優里',
    nickname: 'Yuttan (ゆったん)',
    birthday: '1993/07/20',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'A',
    age: '27 Years Old',
    height: '157cm',
    imgUrl: '/nogizaka46/members/1st-Saito Yuri-Tokyo Japan.jpg',
    birthdayStr: '1993/07/20'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/1/1a/IkutaKaerimichi.jpg',
    gen: '1st',
    romaji: 'Ikuta Erika',
    kanji: '生田絵梨花',
    nickname: 'Ikuchan (いくちゃん)',
    birthday: '1997/01/22',
    birthPlace: 'North Rhine-Westphalia, Germany',
    bloodType: 'A',
    age: '23 Years Old',
    height: '160cm',
    imgUrl: '/nogizaka46/members/1st-Ikuta Erika-North Rhine-Westphalia Germany.jpg',
    birthdayStr: '1997-01-22'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/4/4d/SaitoAsukaKaerimichi.jpg',
    gen: '1st',
    romaji: 'Saito Asuka',
    kanji: '齋藤飛鳥',
    nickname: 'Ashurin (あしゅりん)',
    birthday: '1998/08/10',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'O',
    age: '21 Years Old',
    height: '158cm',
    imgUrl: '/nogizaka46/members/1st-Saito Asuka-Tokyo Japan.jpg',
    birthdayStr: '1998-08-10'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/7/72/OzonoKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Ozono Momoko',
    kanji: '大園桃子',
    nickname: '**',
    birthday: '1999/09/13',
    birthPlace: 'Kagoshima, Japan',
    bloodType: 'O',
    age: '20 Years Old',
    height: '156cm',
    imgUrl: '/nogizaka46/members/3rd-Ozono Momoko-Kagoshima Japan.jpg',
    birthdayStr: '1999-09-13'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/a/a9/MatsumuraKaerimichi.jpg',
    gen: '1st',
    romaji: 'Matsumura Sayuri',
    kanji: '松村沙友理',
    nickname: 'Sayurin (さゆりん)  Mattsun (まっつん)  Sayuringo (さず林檎)',
    birthday: '1992/08/27',
    birthPlace: 'Osaka, Japan',
    bloodType: 'B',
    age: '27 Years Old',
    height: '164cm',
    imgUrl: '/nogizaka46/members/1st-Matsumura Sayuri-Osaka Japan.jpg',
    birthdayStr: '1992-08-27'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/b/bc/KuboKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Kubo Shiori',
    kanji: '久保史緒里',
    nickname: 'Kubochan (くぼちゃん)',
    birthday: '2001/07/14',
    birthPlace: 'Miyagi, Japan',
    bloodType: 'O',
    age: '18 Years Old',
    height: '159cm',
    imgUrl: '/nogizaka46/members/3rd-Kubo Shiori-Miyagi Japan.jpg',
    birthdayStr: '2001-07-14'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/0/09/HashimotoHadashi.jpg',
    gen: '1st',
    romaji: 'Hashimoto Nanami',
    kanji: '橋本 奈々未',
    nickname: 'Nanamin (ななみん)',
    birthday: '1993/02/20',
    birthPlace: 'Asahikawa, Hokkaido, Japan',
    bloodType: 'B',
    age: '26 Years Old',
    height: '163cm',
    imgUrl: '/nogizaka46/members/1st-Hashimoto Nanami-Asahikawa Hokkaido Japan.jpg',
    birthdayStr: '1993-02-20'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/index.php/File:SakuraiKaerimichi.jpg',
    gen: '1st',
    romaji: 'Sakurai Reika',
    kanji: '桜井玲香',
    nickname: 'Reika (れいか)',
    birthday: '1994/05/16',
    birthPlace: 'Kanagawa, Japan',
    bloodType: 'A',
    age: '26 Years Old',
    height: '156cm',
    imgUrl: '/nogizaka46/members/1st-Sakurai Reika-Kanagawa Japan.jpg',
    birthdayStr: '1994-05-16'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/index.php/File:IkomaInfluencer.jpg',
    gen: '1st',
    romaji: 'Ikoma Rina',
    kanji: '生駒里奈 (\tいこま りな)',
    nickname: 'Ikomachan (いこまちゃん)',
    birthday: '1995/12/29',
    birthPlace: 'Yurihonjo, Akita, Japan',
    bloodType: 'AB',
    age: '24 Years Old',
    height: '153cm',
    imgUrl: '/nogizaka46/members/1st-Ikoma Rina-Yurihonjo Akita Japan.jpg',
    birthdayStr: '1995-12-29'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/5/5d/IkomaInfluencer.jpg',
    gen: '1st',
    romaji: 'Etō Misa',
    kanji: '衛藤美彩 (\tえとう みさ)',
    nickname: 'Misamisa (みさみさ)',
    birthday: '1993/01/04',
    birthPlace: 'Oita City, Oita, Japan',
    bloodType: 'AB',
    age: '27 Years Old',
    height: '163cm',
    imgUrl: '/nogizaka46/members/1st-Eto Misa-Oita City Oita Japan.jpg',
    birthdayStr: '1993-01-04'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/c/c7/FukagawaHarujion.jpg',
    gen: '1st',
    romaji: 'Fukagawa Mai',
    kanji: '深川麻衣',
    nickname: 'Maimai (まいまい)',
    birthday: '1991/03/29',
    birthPlace: 'Shizuoka, Japan',
    bloodType: 'O',
    age: '28 Years Old',
    height: '162cm',
    imgUrl: '/nogizaka46/members/1st-Fukagawa Mai-Shizuoka Japan.jpg',
    birthdayStr: '1991-03-29'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/8/82/AkimotoKaerimichi.jpg',
    gen: '1st',
    romaji: 'Akimoto Manatsu',
    kanji: '秋元真夏',
    nickname: 'Manatsu (まなつ)',
    birthday: '1993/08/20',
    birthPlace: 'Miyagi, Japan',
    bloodType: 'B',
    age: '26 Years Old',
    height: '154cm',
    imgUrl: '/nogizaka46/members/1st-Akimoto Manatsu-Miyagi Japan.jpg',
    birthdayStr: '1993-08-20'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/1/17/InoueKaerimichi.jpg',
    gen: '1st',
    romaji: 'Inoue Sayuri',
    kanji: '井上小百合',
    nickname: 'Sayu-nyan (さゆにゃん)',
    birthday: '1994/12/14',
    birthPlace: 'Saitama, Japan',
    bloodType: 'B',
    age: '25 Years Old',
    height: '156cm',
    imgUrl: '/nogizaka46/members/1st-Inoue Sayuri-Saitama Japan.jpg',
    birthdayStr: '1994-12-14'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/3/34/TakayamaKaerimichi.jpg',
    gen: '1st',
    romaji: 'Takayama Kazumi',
    kanji: '高山一実',
    nickname: 'Kazumin (かずみん)',
    birthday: '1994/02/08',
    birthPlace: 'Chiba, Japan',
    bloodType: 'A',
    age: '26 Years Old',
    height: '162cm',
    imgUrl: '/nogizaka46/members/1st-Takayama Kazumi-Chiba Japan.jpg',
    birthdayStr: '1994-02-08'
  },
  {
    url: 'http://stage48.net/wiki/images/3/31/NakadaKaerimichi.jpg',
    gen: '1st',
    romaji: 'Nakada Kana',
    kanji: '中田花奈',
    nickname: 'Kanarin (かなりん)',
    birthday: '1994/08/06',
    birthPlace: 'Saitama, Japan',
    bloodType: 'A',
    age: '25 Years Old',
    height: '158cm',
    imgUrl: '/nogizaka46/members/1st-Nakada Kana-Saitama Japan.jpg',
    birthdayStr: '1994-08-06'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/f/fd/HiguchiKaerimichi.jpg',
    gen: '1st',
    romaji: 'Higuchi Hina',
    kanji: '樋口日奈',
    nickname: 'Hinachima (ひなちま)',
    birthday: '1998/01/31',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'A',
    age: '22 Years Old',
    height: '159cm',
    imgUrl: '/nogizaka46/members/1st-Higuchi Hina-Tokyo Japan.jpg',
    birthdayStr: '1998-01-31'
  },
  {
    url: 'http://stage48.net/wiki/images/3/32/WadaKaerimichi.jpg',
    gen: '1st',
    romaji: 'Wada Maaya',
    kanji: '和田まあや',
    nickname: 'Maaya (まあや)',
    birthday: '1998/04/23',
    birthPlace: 'Hiroshima, Japan',
    bloodType: 'O',
    age: '21 Years Old',
    height: '160cm',
    imgUrl: '/nogizaka46/members/1st-Wada Maaya-Hiroshima Japan.jpg',
    birthdayStr: '1998-04-23'
  },
  {
    url: 'http://stage48.net/wiki/images/3/3b/ItoJunnaKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Ito Junna',
    kanji: '伊藤純奈',
    nickname: 'Junna (じゅんな)',
    birthday: '1998/11/30',
    birthPlace: 'Kanagawa, Japan',
    bloodType: 'A',
    age: '21',
    height: '166cm',
    imgUrl: '/nogizaka46/members/2nd-Ito Junna-Kanagawa Japan.jpg',
    birthdayStr: '1998-11-30'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/1/18/KitanoKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Kitano Hinako',
    kanji: '北野日奈子',
    nickname: 'Kiichan (きいちゃん)',
    birthday: '1996/07/17',
    birthPlace: 'Hokkaido, Japan',
    bloodType: 'O',
    age: '23',
    height: '158cm',
    imgUrl: '/nogizaka46/members/2nd-Kitano Hinako-Hokkaido Japan.jpg',
    birthdayStr: '1996-07-17'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/c/c5/SasakiKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Sasaki Kotoko',
    kanji: '佐々木琴子',
    nickname: 'Kotoko (ことこ)',
    birthday: '1998/08/28',
    birthPlace: 'Saitama, Japan',
    bloodType: 'A',
    age: '21',
    height: '163cm',
    imgUrl: '/nogizaka46/members/2nd-Sasaki Kotoko-Saitama Japan.jpg',
    birthdayStr: '1998-08-28'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/6/64/ShinuchiKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Shinuchi Mai',
    kanji: '新内眞衣',
    nickname: 'Maichun (まいちゅん)',
    birthday: '1992/01/22',
    birthPlace: 'Saitama, Japan',
    bloodType: 'B',
    age: '28',
    height: '165cm',
    imgUrl: '/nogizaka46/members/2nd-Shinuchi Mai-Saitama Japan.jpg',
    birthdayStr: '1992-01-22'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/9/94/SuzukiKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Suzuki Ayane',
    kanji: '鈴木絢音',
    nickname: 'Aachan (あーちゃん)',
    birthday: '1999/03/05',
    birthPlace: 'Akita, Japan',
    bloodType: 'O',
    age: '20',
    height: '160cm',
    imgUrl: '/nogizaka46/members/2nd-Suzuki Ayane-Akita Japan.jpg',
    birthdayStr: '1999-03-05'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/e/ea/TeradaKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Terada Ranze',
    kanji: '寺田蘭世',
    nickname: 'Ranran (らんらん)',
    birthday: '1998/09/23',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'O',
    age: '21',
    height: '155cm',
    imgUrl: '/nogizaka46/members/2nd-Terada Ranze-Tokyo Japan.jpg',
    birthdayStr: '1998-09-23'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/7/74/HoriKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Hori Miona',
    kanji: '堀未央奈',
    nickname: 'Miona (みおな)',
    birthday: '1996/10/15',
    birthPlace: 'Gifu, Japan',
    bloodType: 'O',
    age: '23',
    height: '160cm',
    imgUrl: '/nogizaka46/members/2nd-Hori Miona-Gifu Japan.jpg',
    birthdayStr: '1996-10-15'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/7/76/YamazakiKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Yamazaki Rena',
    kanji: '山﨑怜奈',
    nickname: 'Renachi (れなち)',
    birthday: '1997/05/21',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'B',
    age: '22',
    height: '164cm',
    imgUrl: '/nogizaka46/members/2nd-Yamazaki Rena-Tokyo Japan.jpg',
    birthdayStr: '1997-05-21'
  },
  {
    url: 'http://stage48.net/wiki/images/d/d4/WatanabeKaerimichi.jpg',
    gen: '2nd',
    romaji: 'Watanabe Miria',
    kanji: '渡辺みり愛',
    nickname: 'Miririn (みりりん)  Miichan (みーちゃん)  Nabechan (なべちゃん)  Miriatan (みりあたん)',
    birthday: '1999/11/01',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'O',
    age: '20',
    height: '153cm',
    imgUrl: '/nogizaka46/members/2nd-Watanabe Miria-Tokyo Japan.jpg',
    birthdayStr: '1999-11-01'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/e/ee/ItoRiriaKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Ito Riria',
    kanji: '伊藤理々杏',
    nickname: 'Ririan (りりあん)',
    birthday: '2002/10/08',
    birthPlace: 'Okinawa, Japan',
    bloodType: 'B',
    age: '17 Years Old',
    height: '154cm',
    imgUrl: '/nogizaka46/members/3rd-Ito Riria-Okinawa Japan.jpg',
    birthdayStr: '2002-10-08'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/5/56/IwamotoKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Iwamoto Renka',
    kanji: '岩本蓮加',
    nickname: 'Rentan (れんたん)',
    birthday: '2004/02/02',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'B',
    age: '16 Years Old',
    height: '157cm',
    imgUrl: '/nogizaka46/members/3rd-Iwamoto Renka-Tokyo Japan.jpg',
    birthdayStr: '2004-02-02'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/7/7e/UmezawaKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Umezawa Minami',
    kanji: '梅澤美波',
    nickname: 'Minamin (みなみん)',
    birthday: '1999/01/06',
    birthPlace: 'Kanagawa, Japan',
    bloodType: 'A',
    age: '21 Years Old',
    height: '170cm',
    imgUrl: '/nogizaka46/members/3rd-Umezawa Minami-Kanagawa Japan.jpg',
    birthdayStr: '1999-01-06'
  },
  {
    url: 'http://stage48.net/wiki/images/9/99/SakaguchiKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Sakaguchi Tamami',
    kanji: '阪口珠美',
    nickname: '**',
    birthday: '2001/11/10',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'A',
    age: '18 Years Old',
    height: '161cm',
    imgUrl: '/nogizaka46/members/3rd-Sakaguchi Tamami-Tokyo Japan.jpg',
    birthdayStr: '2001-11-10'
  },
  {
    url: 'http://stage48.net/wiki/images/2/27/SatoKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Sato Kaede',
    kanji: '佐藤楓',
    nickname: 'Denchan (でんちゃん)',
    birthday: '1998/03/23',
    birthPlace: 'Aichi, Japan',
    bloodType: 'A',
    age: '21 Years Old',
    height: '161cm',
    imgUrl: '/nogizaka46/members/3rd-Sato Kaede-Aichi Japan.jpg',
    birthdayStr: '1998-03-23'
  },
  {
    url: 'http://stage48.net/wiki/images/e/e1/NakamuraKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Nakamura Reno',
    kanji: '中村麗乃',
    nickname: '**',
    birthday: '2001/09/27',
    birthPlace: 'Tokyo, Japan',
    bloodType: '**',
    age: '18 Years Old',
    height: '167cm',
    imgUrl: '/nogizaka46/members/3rd-Nakamura Reno-Tokyo Japan.jpg',
    birthdayStr: '2001-09-27'
  },
  {
    url: 'http://stage48.net/wiki/images/9/9b/MukaiKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Mukai Hazuki',
    kanji: '向井葉月',
    nickname: '**',
    birthday: '1999/08/23',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'A',
    age: '20 Years Old',
    height: '152cm',
    imgUrl: '/nogizaka46/members/3rd-Mukai Hazuki-Tokyo Japan.jpg',
    birthdayStr: '1999-08-23'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/7/78/YamashitaKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Yamashita Mizuki',
    kanji: '山下美月',
    nickname: 'Zukkii (づっきー)',
    birthday: '1999/07/26',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'O',
    age: '20 Years Old',
    height: '159cm',
    imgUrl: '/nogizaka46/members/3rd-Yamashita Mizuki-Tokyo Japan.jpg',
    birthdayStr: '1999-07-26'
  },
  {
    url: 'http://stage48.net/wiki/images/e/e8/YoshidaKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Yoshida Ayano Christie',
    kanji: '吉田綾乃クリスティー',
    nickname: 'Ayatii (あやてぃー)',
    birthday: '1995/09/06',
    birthPlace: 'Oita, Japan',
    bloodType: 'A',
    age: '24 Years Old',
    height: '161cm',
    imgUrl: '/nogizaka46/members/3rd-Yoshida Ayano Christie-Oita Japan.jpg',
    birthdayStr: '1995-09-06'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/0/0a/YodaKaerimichi.jpg',
    gen: '3rd',
    romaji: 'Yoda Yuki',
    kanji: '与田祐希',
    nickname: 'Yodachan (よだちゃん)',
    birthday: '2000/05/05',
    birthPlace: 'Fukuoka, Japan',
    bloodType: 'O',
    age: '19 Years Old',
    height: '152cm',
    imgUrl: '/nogizaka46/members/3rd-Yoda Yuki-Fukuoka Japan.jpg',
    birthdayStr: '2000-05-05'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/f/ff/EndoDebut.jpg',
    gen: '4th',
    romaji: 'Endo Sakura',
    kanji: '遠藤 さくら',
    nickname: 'Sakura (さくら)',
    birthday: '2001/10/03',
    birthPlace: 'Aichi, Japan',
    bloodType: '**',
    age: '18 Years Old',
    height: '160cm',
    imgUrl: '/nogizaka46/members/4th-Endo Sakura-Aichi Japan.jpg',
    birthdayStr: '2001-10-03'
  },
  {
    url: 'http://stage48.net/wiki/images/8/85/KakiDebut.jpg',
    gen: '4th',
    romaji: 'Kaki Haruka',
    kanji: '賀喜 遥香',
    nickname: 'Kakki (かっきー)',
    birthday: '2001/08/08',
    birthPlace: 'Tochigi, Japan',
    bloodType: 'A',
    age: '18 Years Old',
    height: '166cm',
    imgUrl: '/nogizaka46/members/4th-Kaki Haruka-Tochigi Japan.jpg',
    birthdayStr: '2001-08-08'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/0/0b/KakehashiDebut.jpg',
    gen: '4th',
    romaji: 'Kakehashi Sayaka',
    kanji: '掛橋 沙耶香',
    nickname: 'Saachan (さーちゃん)',
    birthday: '2002/11/20',
    birthPlace: 'Okayama, Japan',
    bloodType: 'B',
    age: '17 Years Old',
    height: '156cm',
    imgUrl: '/nogizaka46/members/4th-Kakehashi Sayaka-Okayama Japan.jpg',
    birthdayStr: '2002-11-20'
  },
  {
    url: 'http://stage48.net/wiki/images/1/19/KanagawaDebut.jpg',
    gen: '4th',
    romaji: 'Kanagawa Saya',
    kanji: '金川 紗耶',
    nickname: 'Yanchan (やんちゃん)',
    birthday: '2001/10/31',
    birthPlace: 'Hokkaido, Japan',
    bloodType: 'O',
    age: '18 Years Old',
    height: '164cm',
    imgUrl: '/nogizaka46/members/4th-Kanagawa Saya-Hokkaido Japan.jpg',
    birthdayStr: '2001-10-31'
  },
  {
    url: 'http://stage48.net/wiki/images/7/71/KitagawaDebut.jpg',
    gen: '4th',
    romaji: 'Kitagawa Yuri',
    kanji: '北川悠理',
    nickname: 'Yurichan (ゆりちゃん)',
    birthday: '2001/08/08',
    birthPlace: 'Tokyo, Japan',
    bloodType: '**',
    age: '18 Years Old',
    height: '163cm',
    imgUrl: '/nogizaka46/members/4th-Kitagawa Yuri-Tokyo Japan.jpg',
    birthdayStr: '2001-08-08'
  },
  {
    url: 'http://stage48.net/wiki/images/9/9f/ShibataDebut.jpg',
    gen: '4th',
    romaji: 'Shibata Yuna',
    kanji: '柴田 柚菜',
    nickname: 'Yunchan (ゆんちゃん)',
    birthday: '2003/03/03',
    birthPlace: 'Chiba, Japan',
    bloodType: 'A',
    age: '16 Years Old',
    height: '160cm',
    imgUrl: '/nogizaka46/members/4th-Shibata Yuna-Chiba Japan.jpg',
    birthdayStr: '2003-03-03'
  },
  {
    url: 'http://stage48.net/wiki/images/2/21/SeimiyaDebut.jpg',
    gen: '4th',
    romaji: 'Seimiya Rei',
    kanji: '清宮 レイ',
    nickname: 'Reichan (れいちゃん)',
    birthday: '2003/08/01',
    birthPlace: 'Saitama, Japan',
    bloodType: 'O',
    age: '16 Years Old',
    height: '162cm',
    imgUrl: '/nogizaka46/members/4th-Seimiya Rei-Saitama Japan.jpg',
    birthdayStr: '2003-08-01'
  },
  {
    url: 'http://stage48.net/wiki/images/9/9b/TamuraDebut.jpg',
    gen: '4th',
    romaji: 'Tamura Mayu',
    kanji: '田村 真佑',
    nickname: 'Mayutan (まゆたん)',
    birthday: '1999/01/12',
    birthPlace: 'Saitama, Japan',
    bloodType: 'A',
    age: '21 Years Old',
    height: '158cm',
    imgUrl: '/nogizaka46/members/4th-Tamura Mayu-Saitama Japan.jpg',
    birthdayStr: '1999-01-12'
  },
  {
    isTop: 1,
    url: 'http://stage48.net/wiki/images/2/2e/TsutsuiDebut.jpg',
    gen: '4th',
    romaji: 'Tsutsui Ayame',
    kanji: '筒井 あやめ',
    nickname: 'Ayamen (あやめん)',
    birthday: '2004/06/08',
    birthPlace: 'Aichi, Japan',
    bloodType: 'O',
    age: '15 Years Old',
    height: '160cm',
    imgUrl: '/nogizaka46/members/4th-Tsutsui Ayame-Aichi Japan.jpg',
    birthdayStr: '2004-06-08'
  },
  {
    url: 'http://stage48.net/wiki/images/d/d9/HayakawaDebut.jpg',
    gen: '4th',
    romaji: 'Hayakawa Seira',
    kanji: '早川 聖来',
    nickname: 'Seira (せいら)',
    birthday: '2000/08/24',
    birthPlace: 'Osaka, Japan',
    bloodType: 'A',
    age: '19 Years Old',
    height: '164cm',
    imgUrl: '/nogizaka46/members/4th-Hayakawa Seira-Osaka Japan.jpg',
    birthdayStr: '2000-08-24'
  },
  {
    url: 'http://stage48.net/wiki/images/e/e0/YakuboDebut.jpg',
    gen: '4th',
    romaji: 'Yakubo Mio',
    kanji: '矢久保 美緒',
    nickname: 'Yakubo (やくぼ)',
    birthday: '2002/08/14',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'B',
    age: '17 Years Old',
    height: '152cm',
    imgUrl: '/nogizaka46/members/4th-Yakubo Mio-Tokyo Japan.jpg',
    birthdayStr: '2002-08-14'
  },
  {
    url: '',
    gen: '4th+',
    romaji: 'Yumiki Nao',
    kanji: '弓木 奈於',
    nickname: 'Naochan (なおちゃん)',
    birthday: '1999/02/03',
    birthPlace: 'Tokyo, Japan',
    bloodType: 'A',
    age: '21 Years Old',
    height: '165cm',
    imgUrl: '/nogizaka46/members/4th-plus-Yumiki Nao-Kyoto Japan.jpg',
    birthdayStr: '1999-02-03'
  },
  {
    url: '',
    gen: '4th+',
    romaji: 'Matsuo Miyu',
    kanji: '松尾 美佑',
    nickname: 'Miyurin (みゆりん)',
    birthday: '2004/01/03',
    birthPlace: 'Chiba, Japan',
    bloodType: 'O',
    age: '16 Years Old',
    height: '165cm',
    imgUrl: '/nogizaka46/members/4th-plus-Matsuo Miyu-Chiba Japan.jpg',
    birthdayStr: '2004-01-03'
  },
  {
    url: '',
    gen: '4th+',
    romaji: 'Hayashi Runa',
    kanji: '林 瑠奈',
    nickname: 'Runachan (るなちゃん)',
    birthday: '2003/10/02',
    birthPlace: 'Chiba, Japan',
    bloodType: 'O',
    age: '16 Years Old',
    height: '163cm',
    imgUrl: '/nogizaka46/members/4th-plus-Hayashi Runa-Kanagawa Japan.jpg',
    birthdayStr: '2003-10-02'
  },
  {
    url: '',
    gen: '4th+',
    romaji: 'Sato Rika',
    kanji: '佐藤 璃果',
    nickname: 'Rikachan (りかちゃん)',
    birthday: '2001/08/09',
    birthPlace: 'Iwate, Japan',
    bloodType: 'B',
    age: '18 Years Old',
    height: '158cm',
    imgUrl: '/nogizaka46/members/4th-plus-Sato Rika-Iwate Japan.jpg',
    birthdayStr: '2001-08-09'
  },
  {
    url: '',
    gen: '4th+',
    romaji: 'Kuromi Haruka',
    kanji: '黒見 明香',
    nickname: 'Kuromin (くろみん) or Kuromichan (くろみちゃん)',
    birthday: '2004/01/19',
    birthPlace: 'Hong Kong',
    bloodType: 'B',
    age: '16 Years Old',
    height: '162cm',
    imgUrl: '/nogizaka46/members/4th-plus-Kuromi Haruka-Hong Kong.jpg',
    birthdayStr: '2004-01-19'
  },
];

// function dateToYMD(date) {
//   var d = date.getDate();
//   var m = date.getMonth() + 1; //Month from 0 to 11
//   var y = date.getFullYear();
//   return '' + y + '/' + (m <= 9 ? '0' + m : m) + '/' + (d <= 9 ? '0' + d : d);
// }

// const a = Nogizaka46Members.map(item => ({
//   ...item,
//   birthdayStr: item.birthday,
//   birthday: dateToYMD(new Date(item.birthday)),
// }));

// console.log(JSON.stringify(a, null, 2));

export default Nogizaka46Members;
